<Project>
	<PropertyGroup>
		<RepoRoot>$(MSBuildThisFileDirectory)</RepoRoot>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="all" />
		<AdditionalFiles Include="$(RepoRoot)BannedSymbols.txt" />
	</ItemGroup>
</Project>
