<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Testcontainers.PostgreSql" />
		<PackageReference Include="Testcontainers.XunitV3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\Data\Creomobile.Data.EFCore\Creomobile.Data.EFCore.csproj" />
	</ItemGroup>
</Project>
