<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
	
	<PropertyGroup>
		<Deterministic>true</Deterministic>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
		<Authors>Andrii Glushko</Authors>
		<Company>Creomobile</Company>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>Logo.png</PackageIcon>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/creomobile/Creomobile.Base</RepositoryUrl>
		<PackageProjectUrl>https://github.com/creomobile/Creomobile.Base</PackageProjectUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<PackageTags>creomobile;platform</PackageTags>
		<EnablePackageValidation>true</EnablePackageValidation>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildProjectDirectory)\README.md"
			  Pack="true"
			  PackagePath=""/>
		<None Include="$(RepoRoot)Logo.png"
			  Pack="true"
			  PackagePath=""/>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>$(AssemblyName).UnitTests</_Parameter1>
		</AssemblyAttribute>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>$(AssemblyName).IntegrationTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>
